```{r message=FALSE, warning=FALSE}
#Install and Load RCurl Package
library(curl)
library(tidyverse)

#Not reading from GitHub because it is crashing my R Studio
GAMES = read.csv("Data/games.csv")
GAMES_DETAILS = read.csv("Data/games_details.csv")
TEAMS = read.csv("Data/teams.csv")
PLAYERS = read.csv("Data/players.csv")
```
### CLEANING THE DATA
```{r}
#Clean the date variable in games
GAMES = GAMES %>%
          separate(GAME_DATE_EST, c("YEAR","MONTH","DAY"), sep='-', convert=TRUE, remove=TRUE)
```
```{r}
#Add the date variable to GAME_DETAILS
GAMES_DETAILS = left_join(GAMES_DETAILS, select(GAMES, c("GAME_ID", "YEAR", "MONTH", "DAY")), by="GAME_ID")
```
```{r}
#Clean the player data
PLAYERS = PLAYERS[,c(1,4,5,21)]
names(PLAYERS) = c("PLAYER_NAME","HEIGHT","WEIGHT","YEAR")
PLAYERS$WEIGHT = as.numeric(PLAYERS$WEIGHT)
PLAYERS = PLAYERS %>%
          separate(HEIGHT, c("FEET","INCHES"), sep='-', convert=TRUE, remove=TRUE) %>% 
          mutate(HEIGHT=12*FEET+INCHES) %>%
          select(-c(FEET, INCHES))
```
```{r}
#Add height and weight variables to GAME_DETAILS
GAMES_DETAILS = left_join(GAMES_DETAILS, PLAYERS, by=c("PLAYER_NAME", "YEAR"))
```
```{r}
#Creating the Spread and Total variables
GAMES = mutate(GAMES, Spread=PTS_home-PTS_away, Total=PTS_home+PTS_away)
```
```{r message=FALSE}
#Obtain OREB
OREB = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,OREB) %>%
          transform(OREB = as.numeric(OREB)) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(OREB=sum(OREB,na.rm=T)) %>%
          ungroup()
```
```{r message=FALSE}
#Obtain DREB
DREB = GAMES_DETAILS %>%
          select (TEAM_ABBREVIATION,GAME_ID,TEAM_ID,DREB) %>%
          transform(DREB = as.numeric(DREB)) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(DREB=sum(DREB,na.rm=T)) %>%
          ungroup()
```
```{r message=FALSE}
#Obtain EFG%
EFGP = GAMES_DETAILS %>%
          select(TEAM_ABBREVIATION,GAME_ID,TEAM_ID,FGM,FGA,FG3M,FG3A) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(EFGP=(sum(FGM, na.rm=T)+0.5*sum(FG3M, na.rm=T))/sum(FGA, na.rm=T)) %>%
          ungroup()
```
```{r message=FALSE}
#Obtain TOV%
TOVP = GAMES_DETAILS %>%
          select(TEAM_ABBREVIATION,GAME_ID,TEAM_ID,TO,FGA,FTA) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(TOVP=sum(TO, na.rm=T)/(sum(FGA, na.rm=T)+0.44*sum(FTA, na.rm=T)+sum(TO, na.rm=T))) %>%
          ungroup()
```
```{r message=FALSE}
#Obtain FTR
FTR = GAMES_DETAILS %>%
          select(TEAM_ABBREVIATION,GAME_ID,TEAM_ID,FTA,FGA) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(FTR=sum(FTA, na.rm=T)/sum(FGA, na.rm=T)) %>%
          ungroup()
```
```{r}
#Calculate average height and weight of all players in the PLAYERS dataset
avg_height = mean(PLAYERS$HEIGHT, na.rm=T)
avg_weight = mean(PLAYERS$WEIGHT, na.rm=T)
```
```{r}
#Create identifier variables: ABOVE_AVG_HEIGHT & ABOVE_AVG_WEIGHT
GAMES_DETAILS$ABOVE_AVG_HEIGHT = ifelse(GAMES_DETAILS$HEIGHT > avg_height, 1, 0)
GAMES_DETAILS$ABOVE_AVG_WEIGHT = ifelse(GAMES_DETAILS$WEIGHT > avg_weight, 1, 0)
```
```{r message=FALSE}
#Obtain percentage above average height and percentage above average weight
HEIGHT_PROP = GAMES_DETAILS %>%
          select(TEAM_ABBREVIATION,GAME_ID,TEAM_ID,ABOVE_AVG_HEIGHT) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(HEIGHT_PROP=sum(ABOVE_AVG_HEIGHT, na.rm=T)/n()) %>%
          ungroup()
WEIGHT_PROP = GAMES_DETAILS %>%
          select(TEAM_ABBREVIATION,GAME_ID,TEAM_ID,ABOVE_AVG_WEIGHT) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(WEIGHT_PROP=sum(ABOVE_AVG_WEIGHT, na.rm=T)/n()) %>%
          ungroup()
```
```{r message=FALSE}
# Obtain AVG_HEIGHT and AVG_WEIGHT
AVG_HEIGHT = GAMES_DETAILS %>%
          select(TEAM_ABBREVIATION,GAME_ID,TEAM_ID,HEIGHT) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(AVG_HEIGHT = mean(HEIGHT, na.rm=T)) %>%
          ungroup()
AVG_WEIGHT = GAMES_DETAILS %>%
          select(TEAM_ABBREVIATION,GAME_ID,TEAM_ID,WEIGHT) %>%
          group_by(TEAM_ABBREVIATION,GAME_ID,TEAM_ID) %>%
          summarize(AVG_WEIGHT = mean(WEIGHT, na.rm=T)) %>%
          ungroup()
```
```{r}
#Add OREB to GAMES
GAMES = left_join(GAMES, select(OREB, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(OREB_home = OREB) %>%
          left_join(select(OREB, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(OREB_away = OREB) %>%
          mutate(OREB = OREB_home + OREB_away)
```
```{r}
#Add DREB to GAMES
GAMES = left_join(GAMES, select(DREB, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(DREB_home = DREB) %>%
          left_join(select(DREB, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(DREB_away = DREB) %>%
          mutate(DREB = DREB_home + DREB_away)
```
```{r}
#Create OREB% and DREB% variables
GAMES = GAMES %>%
          mutate(OREBP_home=OREB_home/(OREB_home+DREB_away)) %>%
          mutate(OREBP_away=OREB_away/(OREB_away+DREB_home)) %>%
          mutate(DREBP_home=DREB_home/(DREB_home+OREB_away)) %>%
          mutate(DREBP_away=DREB_away/(DREB_away+OREB_home))
```
```{r}
#Add EFG% to GAMES
GAMES = left_join(GAMES, select(EFGP, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(EFGP_home = EFGP) %>%
          left_join(select(EFGP, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(EFGP_away = EFGP)
```
```{r}
#Add TOV% to GAMES
GAMES = left_join(GAMES, select(TOVP, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(TOVP_home = TOVP) %>%
          left_join(select(TOVP, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(TOVP_away = TOVP)
```
```{r}
#Add FTR to GAMES
GAMES = left_join(GAMES, select(FTR, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(FTR_home = FTR) %>%
          left_join(select(FTR, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(FTR_away = FTR)
```
```{r}
# Add HEIGHT_PROP and WEIGHT_PROP
GAMES = left_join(GAMES, select(HEIGHT_PROP, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(HEIGHT_PROP_home = HEIGHT_PROP) %>%
          left_join(select(HEIGHT_PROP, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(HEIGHT_PROP_away = HEIGHT_PROP)
GAMES = left_join(GAMES, select(WEIGHT_PROP, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(WEIGHT_PROP_home = WEIGHT_PROP) %>%
          left_join(select(WEIGHT_PROP, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(WEIGHT_PROP_away = WEIGHT_PROP)
```
```{r}
#Add AVG_HEIGHT and AVG_WEIGHT
GAMES = left_join(GAMES, select(AVG_HEIGHT, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(AVG_HEIGHT_home = AVG_HEIGHT) %>%
          left_join(select(AVG_HEIGHT, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(AVG_HEIGHT_away = AVG_HEIGHT)
GAMES = left_join(GAMES, select(AVG_WEIGHT, -TEAM_ABBREVIATION), by = c("GAME_ID", "HOME_TEAM_ID"="TEAM_ID")) %>%
          rename(AVG_WEIGHT_home = AVG_WEIGHT) %>%
          left_join(select(AVG_WEIGHT, -TEAM_ABBREVIATION), by = c("GAME_ID", "VISITOR_TEAM_ID"="TEAM_ID")) %>%
          rename(AVG_WEIGHT_away = AVG_WEIGHT)
```
```{r}
#Create difference variables
GAMES$OREB_diff = GAMES$OREB_home - GAMES$OREB_away
GAMES$DREB_diff = GAMES$DREB_home - GAMES$DREB_away
GAMES$OREBP_diff = GAMES$OREBP_home - GAMES$OREBP_away
GAMES$DREBP_diff = GAMES$DREBP_home - GAMES$DREBP_away
GAMES$EFGP_diff = GAMES$EFGP_home - GAMES$EFGP_away
GAMES$TOVP_diff = GAMES$TOVP_home - GAMES$TOVP_away
GAMES$FTR_diff = GAMES$FTR_home - GAMES$FTR_away
GAMES$HEIGHT_PROP_diff = GAMES$HEIGHT_PROP_home - GAMES$HEIGHT_PROP_away
GAMES$WEIGHT_PROP_diff = GAMES$WEIGHT_PROP_home - GAMES$WEIGHT_PROP_away
GAMES$AVG_HEIGHT_diff = GAMES$AVG_HEIGHT_home - GAMES$AVG_HEIGHT_away
GAMES$AVG_WEIGHT_diff = GAMES$AVG_WEIGHT_home - GAMES$AVG_WEIGHT_away
```
```{r}
GAMES = GAMES[complete.cases(GAMES),]
```

##Lasso Regression 

```{r eval=TRUE}
library(tidyverse)
gamesmod<-GAMES%>%
  select(FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away,Total, OREB_home, OREB_away, OREB, DREB, DREB_home, DREB_away, EFGP_home,EFGP_away,TOVP_home, TOVP_away, FTR_home, FTR_away, HEIGHT_PROP_home, HEIGHT_PROP_home, HEIGHT_PROP_away, WEIGHT_PROP_home, WEIGHT_PROP_away, AVG_HEIGHT_home, AVG_HEIGHT_away,  AVG_WEIGHT_home, AVG_WEIGHT_away, OREB_diff, DREB_diff, OREBP_diff, DREBP_diff, EFGP_diff, TOVP_diff, FTR_diff, HEIGHT_PROP_diff, WEIGHT_PROP_diff, AVG_HEIGHT_diff, AVG_WEIGHT_diff)

library(glmnet)
library(caret)
library(mlr)

gamesmatrix<-data.matrix(gamesmod, rownames.force = NA)
#view(gamesmatrix)
gamesmod1<-as.data.frame(GAMES)
gamesmodspread<-gamesmod1$Spread

fit<-glmnet(gamesmatrix,gamesmodspread)

plot(fit)
```

###Crossfit Validation 

```{r eval=TRUE}
cvfit <- cv.glmnet(gamesmatrix,gamesmodspread, type.measure = "class")
plot(cvfit)

```



```{r eval=TRUE}
best<-cvfit$lambda.min
predict(fit, s= best, type= "coefficients")

```
```{r eval=TRUE}
pred.mod<-predict(fit,newx= gamesmatrix, s= best)
spread.orig<-GAMES$Spread

comp<-data.frame(pred.mod, spread.orig)

comp
```
```{r eval=TRUE}
summary(fit)
```






```{r eval=TRUE}
library(ggplot2)

ggplot(comp,aes(x=X1, y=spread.orig)) +
  geom_point()

cor(pred.mod, spread.orig)
```



```{r}
gamestotal.mod<-GAMES %>%
  mutate(logtotal = log(Total))

view(gamestotal.mod)
```


```{r eval=TRUE}
library(tidyverse)
gamesmod2<-gamestotal.mod%>%
  select(PTS_home,FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away,OREB_home, OREB_away, OREB, DREB, DREB_home, DREB_away, EFGP_home,EFGP_away,TOVP_home, TOVP_away, FTR_home, FTR_away, HEIGHT_PROP_home, HEIGHT_PROP_home, HEIGHT_PROP_away, WEIGHT_PROP_home, WEIGHT_PROP_away, AVG_HEIGHT_home, AVG_HEIGHT_away,  AVG_WEIGHT_home, AVG_WEIGHT_away, OREB_diff, DREB_diff, OREBP_diff, DREBP_diff, EFGP_diff, TOVP_diff, FTR_diff, HEIGHT_PROP_diff, WEIGHT_PROP_diff, AVG_HEIGHT_diff, AVG_WEIGHT_diff)

library(glmnet)
library(caret)
library(mlr)

gamesmatrix1<-data.matrix(gamesmod2, rownames.force = NA)
#view(gamesmatrix)
gamesmod3<-as.data.frame(gamestotal.mod)
gamesmodtotal<-gamesmod3$logtotal

fit1<-glmnet(gamesmatrix1,gamesmodtotal)

plot(fit1)
```
###Crossfit Validation 

```{r eval=TRUE}
cvfit1 <- cv.glmnet(gamesmatrix1,gamesmodtotal, type.measure = "class")
plot(cvfit1)

```

```{r eval=TRUE}
best1<-cvfit1$lambda.min
predict(fit1, s= best1, type= "coefficients")

```

```{r eval=TRUE}
pred.mod1<-predict(fit1,newx= gamesmatrix1, s= best1)
pred.mod1exp<-exp(pred.mod1)
total.orig<-GAMES$Total

comp1<-data.frame(pred.mod1exp, total.orig)

comp1

cor(pred.mod1exp,total.orig)
```

```{r eval=TRUE}
library(ggplot2)

ggplot(comp1,aes(x=X1, y=total.orig)) +
  geom_point()

```


```{r}
gamesoreb.mod<-GAMES %>%
  mutate(logoreb = log(OREB))
```


```{r eval=TRUE}
library(tidyverse)
gamesmod3<-gamesoreb.mod%>%
  select(PTS_home, PTS_away, Total, Spread, FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away,OREB_home, DREB, DREB_home, DREB_away, EFGP_home,EFGP_away,TOVP_home, TOVP_away, FTR_home, FTR_away, HEIGHT_PROP_home, HEIGHT_PROP_home, HEIGHT_PROP_away, WEIGHT_PROP_home, WEIGHT_PROP_away, AVG_HEIGHT_home, AVG_HEIGHT_away,  AVG_WEIGHT_home, AVG_WEIGHT_away, OREB_diff, DREB_diff, OREBP_diff, DREBP_diff, EFGP_diff, TOVP_diff, FTR_diff, HEIGHT_PROP_diff, WEIGHT_PROP_diff, AVG_HEIGHT_diff, AVG_WEIGHT_diff)

library(glmnet)
library(caret)
library(mlr)

gamesmatrix2<-data.matrix(gamesmod3, rownames.force = NA)
#view(gamesmatrix)
gamesmod4<-as.data.frame(gamesoreb.mod)
gamesmodoreb<-gamesmod4$logoreb

fit2<-glmnet(gamesmatrix2,gamesmodoreb)

plot(fit2)
```

###Crossfit Validation 

```{r eval=TRUE}
cvfit2 <- cv.glmnet(gamesmatrix2,gamesmodoreb, type.measure = "class")
plot(cvfit2)

```

```{r eval=TRUE}
best2<-cvfit2$lambda.min
predict(fit2, s= best2, type= "coefficients")

```

```{r eval=TRUE}
pred.mod2<-predict(fit2,newx= gamesmatrix2, s= best2)
pred.mod2exp<-exp(pred.mod2)
oreb.orig<-GAMES$OREB

comp2<-data.frame(pred.mod2exp, oreb.orig)

comp2

cor(pred.mod2exp,oreb.orig)
```